
admin_ps_sql_excel_export:
  path: /modules/excel_export/{id_sql_request}
  methods: [GET]
  defaults:
    _controller: 'PsSqlExcelExport\Controller\Admin\AdminPsSqlExcelExportController::export'
    _legacy_controller: 'AdminPsSqlExcelExport'
  requirements:
    id_sql_request: \d+
